### ISSUE TITLE
0.0.1-PREVIEW version on maven central release seems not to match 0.0.1-PREVIEW from master branch

### ISSUE THREAD

**Issue by piotrnk** [Azure/azure-relay-java#44]
Thank you for the development of this library. 
As the library got published to maven central, the versioning management of the code in the master branch would be useful. 
Currently all the last commits in master branch are made under the 0.0.1-PREVIEW version, it's hard to tell what exactly was published to maven central. 
My observation: I noticed that setting of response headers in listener does not work with 0.0.1-PREVIEW from maven central, but it works with the local build of the library.

**Comment by bainian12345** [comment]
0.0.1-PREVIEW from master should match now with the public Maven release.

0.0.2-PREVIEW is also available now from Maven and master with a few bug fixes.
