### ISSUE TITLE
dev version 0.0.1-SNAPSHOT and master on 0.0.2-PREVIEW -> bad version management

### ISSUE THREAD

**Issue by consultantleon** [Azure/azure-relay-java#52]
dev version 0.0.1-SNAPSHOT and master on 0.0.2-PREVIEW -> bad version management!
Dev should be rolled to 0.0.3-SNAPHOT , master should be 0.0.2-RELEASE in my view.
We're building a professional solution on this code, but it appears that the project is not properly managed which is worrying; when will Microsoft provide a proper java API for their Relay & HybridConnection facility? Or is dotnet still the only really supported way?

**Comment by dlstucki** [comment]
Release 0.0.1 was created in March 2019 from the dev branch. At that time this was a fledgling project which didn't even have a separate master branch.

When Release 0.0.2 came around a master branch was created, synced with the latest dev branch, and that was released.

**Comment by dlstucki** [comment]
@bainian12345 did everything from dev branch make it into master? I can't see any obvious merge from dev into master, just that around 6 months ago everything started happening in master only.

**Comment by bainian12345** [comment]
Please ignore the "dev" branch and use the latest master version, 0.0.2-PREVIEW. This library is thoroughly tested and safe to use, although it is yet to be officially announced public, hence the version "0.0.2-PREVIEW".
