### ISSUE TITLE
EofException in long running application with azure-relay 0.0.2-PREVIEW

### ISSUE THREAD

**Issue by piotrnk** [Azure/azure-relay-java#53]
Hello, 
I have built the project with the azure-relay in 0.0.2-PREVIEW version.
In short running application all is fine, but problems start appearing after something like 9h of connection to HybridConnection, please see the logs below (full logs can be downloaded as a zip file from https://drive.google.com/file/d/1WUQjHFP0tqVhT846gHVaqRzOcHEkegmo/view?usp=sharing ).
Problems which occur: 
 
 - org.eclipse.jetty.io.EofException
 - java.io.IOException - Too many open files  at: IOUtil.makePipe(Native Method)

**Log fragment 1:**
      
> 2019-10-03_23:56:40.423- INFO-[WebSocketClient@666573165-3808         
> ]-HybridConnectionListener(TrackingId:e96444d6-7c6a-4ed3-b9c2-14c8442ec37d,
> Address:sb://productXHybridConnection.servicebus.windows.net):
> getToken stop. New token expires at 2019-10-03T22:56:40Z.
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.424-
> INFO-[WebSocketClient@666573165-3808         
> ]-HybridConnectionListener(TrackingId:e96444d6-7c6a-4ed3-b9c2-14c8442ec37d,
> Address:sb://productXHybridConnection.servicebus.windows.net):
> Scheduling Token renewal after PT59M59.576S.
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.425-
> INFO-[autoshutdown-pool-1-thread-193         
> ]-ClientWebSocket(TrackingId:e96444d6-7c6a-4ed3-b9c2-14c8442ec37d,
> Address:sb://productXHybridConnection.servicebus.windows.net) is
> connecting. {com.microsoft.azure.relay.RelayLogger:27}
> 2019-10-03_23:56:40.426- WARN-[WebSocketClient@666573165-3808         
> ]-
> {org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection:565}
> ==> org.eclipse.jetty.io.EofException
>       at: ChannelEndPoint.flush(ChannelEndPoint.java:286)
>   - Cause: java.nio.channels.ClosedChannelException
>       at: SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270)
> 2019-10-03_23:56:40.427-ERROR-[WebSocketClient@666573165-3808         
> ]-ClientWebSocket(TrackingId:e96444d6-7c6a-4ed3-b9c2-14c8442ec37d,
> Address:sb://productXHybridConnection.servicebus.windows.net) is
> throwing an Exception:  {com.microsoft.azure.relay.RelayLogger:62}
> ==> org.eclipse.jetty.io.EofException
>       at: ChannelEndPoint.flush(ChannelEndPoint.java:286)
>   - Cause: java.nio.channels.ClosedChannelException
>       at: SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270)
> 2019-10-03_23:56:40.431- INFO-[WebSocketClient@909969759-3802         
> ]-ClientWebSocket(TrackingId:13588bfa-81c9-4c7b-8b4e-2d9ef52a5beb,
> Address:sb://productXHybridConnection.servicebus.windows.net): is
> closed. Close reason: ExpiredToken: 
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.431-
> INFO-[WebSocketClient@909969759-3802         
> ]-ClientWebSocket(TrackingId:13588bfa-81c9-4c7b-8b4e-2d9ef52a5beb,
> Address:sb://productXHybridConnection.servicebus.windows.net): is
> closing. Close reason: ExpiredToken: 
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.431-
> INFO-[WebSocketClient@909969759-3802         
> ]-com.microsoft.azure.relay.HybridConnectionListener$ControlConnection@5c685b15:
> is disconnected, should reconnect = true
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.432-
> INFO-[WebSocketClient@909969759-3802         
> ]-HybridConnectionListener(TrackingId:13588bfa-81c9-4c7b-8b4e-2d9ef52a5beb,
> Address:sb://productXHybridConnection.servicebus.windows.net):
> getToken start. {com.microsoft.azure.relay.RelayLogger:27}
> 2019-10-03_23:56:40.432- INFO-[WebSocketClient@909969759-3802         
> ]-HybridConnectionListener(TrackingId:13588bfa-81c9-4c7b-8b4e-2d9ef52a5beb,
> Address:sb://productXHybridConnection.servicebus.windows.net):
> getToken stop. New token expires at 2019-10-03T22:56:40Z.
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.433-
> INFO-[WebSocketClient@909969759-3802         
> ]-HybridConnectionListener(TrackingId:13588bfa-81c9-4c7b-8b4e-2d9ef52a5beb,
> Address:sb://productXHybridConnection.servicebus.windows.net):
> Scheduling Token renewal after PT59M59.567S.
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.435-
> INFO-[autoshutdown-pool-1-thread-200         
> ]-ClientWebSocket(TrackingId:13588bfa-81c9-4c7b-8b4e-2d9ef52a5beb,
> Address:sb://productXHybridConnection.servicebus.windows.net) is
> connecting. {com.microsoft.azure.relay.RelayLogger:27}
> 2019-10-03_23:56:40.436- WARN-[WebSocketClient@909969759-3802         
> ]-
> {org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection:565}
> ==> org.eclipse.jetty.io.EofException
>       at: ChannelEndPoint.flush(ChannelEndPoint.java:286)
>   - Cause: java.nio.channels.ClosedChannelException
>       at: SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270)
> 2019-10-03_23:56:40.436-ERROR-[WebSocketClient@909969759-3802         
> ]-ClientWebSocket(TrackingId:13588bfa-81c9-4c7b-8b4e-2d9ef52a5beb,
> Address:sb://productXHybridConnection.servicebus.windows.net) is
> throwing an Exception:  {com.microsoft.azure.relay.RelayLogger:62}
> ==> org.eclipse.jetty.io.EofException
>       at: ChannelEndPoint.flush(ChannelEndPoint.java:286)
>   - Cause: java.nio.channels.ClosedChannelException
>       at: SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270)
> 2019-10-03_23:56:40.462- INFO-[WebSocketClient@1620925453-3792        
> ]-ClientWebSocket(TrackingId:cbf54666-c7b6-4193-bdfc-b0ce9894e15a,
> Address:sb://productXHybridConnection.servicebus.windows.net): is
> closed. Close reason: ExpiredToken: 
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.462-
> INFO-[WebSocketClient@1620925453-3792        
> ]-ClientWebSocket(TrackingId:cbf54666-c7b6-4193-bdfc-b0ce9894e15a,
> Address:sb://productXHybridConnection.servicebus.windows.net): is
> closing. Close reason: ExpiredToken: 
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.462-
> INFO-[WebSocketClient@1620925453-3792        
> ]-com.microsoft.azure.relay.HybridConnectionListener$ControlConnection@51f322ae:
> is disconnected, should reconnect = true
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.463-
> INFO-[WebSocketClient@1620925453-3792        
> ]-HybridConnectionListener(TrackingId:cbf54666-c7b6-4193-bdfc-b0ce9894e15a,
> Address:sb://productXHybridConnection.servicebus.windows.net):
> getToken start. {com.microsoft.azure.relay.RelayLogger:27}
> 2019-10-03_23:56:40.463- INFO-[WebSocketClient@1620925453-3792        
> ]-HybridConnectionListener(TrackingId:cbf54666-c7b6-4193-bdfc-b0ce9894e15a,
> Address:sb://productXHybridConnection.servicebus.windows.net):
> getToken stop. New token expires at 2019-10-03T22:56:40Z.
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.464-
> INFO-[WebSocketClient@1620925453-3792        
> ]-HybridConnectionListener(TrackingId:cbf54666-c7b6-4193-bdfc-b0ce9894e15a,
> Address:sb://productXHybridConnection.servicebus.windows.net):
> Scheduling Token renewal after PT59M59.537S.
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.466-
> INFO-[autoshutdown-pool-1-thread-197         
> ]-ClientWebSocket(TrackingId:cbf54666-c7b6-4193-bdfc-b0ce9894e15a,
> Address:sb://productXHybridConnection.servicebus.windows.net) is
> connecting. {com.microsoft.azure.relay.RelayLogger:27}
> 2019-10-03_23:56:40.475- INFO-[WebSocketClient@499333546-3796         
> ]-ClientWebSocket(TrackingId:761a8a90-9f75-42a8-8e9d-058ac17c1569,
> Address:sb://productXHybridConnection.servicebus.windows.net): is
> closed. Close reason: ExpiredToken: 
> {com.microsoft.azure.relay.RelayLogger:30} 2019-10-03_23:56:40.476-
> INFO-[WebSocketClient@499333546-3796         
> ]-ClientWebSocket(TrackingId:761a8a90-9f75-42a8-8e9d-058ac17c1569,
> Address:sb://productXHybridConnection.servicebus.windows.net): is
> closing. Close reason: ExpiredToken: 
> {com.microsoft.azure.relay.RelayLogger:30}

**Log fragment 2:**

2019-10-05_05:07:57.000- INFO-[Timer-15111                             ]-HybridConnectionListener(TrackingId:dfe99f38-7de7-46b3-a253-cebac5aba399, Address:sb://productXHybridConnection.servicebus.windows.net): getToken stop. New token expires at 2019-10-05T04:07:57Z. {com.microsoft.azure.relay.RelayLogger:30}
2019-10-05_05:07:57.001- INFO-[Timer-15111                             ]-HybridConnectionListener(TrackingId:dfe99f38-7de7-46b3-a253-cebac5aba399, Address:sb://productXHybridConnection.servicebus.windows.net): Scheduling Token renewal after PT59M59.999S. {com.microsoft.azure.relay.RelayLogger:30}
2019-10-05_05:07:57.002- INFO-[autoshutdown-pool-1-thread-11989        ]-ClientWebSocket(TrackingId:dfe99f38-7de7-46b3-a253-cebac5aba399, Address:sb://productXHybridConnection.servicebus.windows.net) is connecting. {com.microsoft.azure.relay.RelayLogger:27}
2019-10-05_05:07:57.002- INFO-[Timer-15111                             ]-HybridConnectionListener(TrackingId:dfe99f38-7de7-46b3-a253-cebac5aba399, Address:sb://productXHybridConnection.servicebus.windows.net): Scheduling Token renewal after PT59M59.998S. {com.microsoft.azure.relay.RelayLogger:30}
2019-10-05_05:07:57.005- WARN-[autoshutdown-pool-1-thread-11989        ]-HybridConnectionListener(TrackingId:dfe99f38-7de7-46b3-a253-cebac5aba399, Address:sb://productXHybridConnection.servicebus.windows.net) is throwing an Exception:  {com.microsoft.azure.relay.RelayLogger:65}
==> java.util.concurrent.CompletionException - java.lang.RuntimeException: Unable to start Client
      at: CompletableFuture.encodeThrowable(CompletableFuture.java:292)
  - Cause: java.lang.RuntimeException - Unable to start Client
      at: ClientContainer.connect(ClientContainer.java:184)
  - Cause: java.io.IOException - Too many open files
      at: IOUtil.makePipe(Native Method)
2019-10-05_05:07:58.000- INFO-[Timer-15113                             ]-HybridConnectionListener(TrackingId:3e60cd83-fbd2-4920-ad80-d7190721b628, Address:sb://productXHybridConnection.servicebus.windows.net): getToken start. {com.microsoft.azure.relay.RelayLogger:27}
2019-10-05_05:07:58.000- INFO-[Timer-15113                             ]-HybridConnectionListener(TrackingId:3e60cd83-fbd2-4920-ad80-d7190721b628, Address:sb://productXHybridConnection.servicebus.windows.net): getToken stop. New token expires at 2019-10-05T04:07:58Z. {com.microsoft.azure.relay.RelayLogger:30}

**Comment by bainian12345** [comment]
@piotrnk Thank you for reporting this issue. Would you mind sharing anything worth noting to reproduce this issue? Especially related to the "Cause: java.io.IOException - Too many open files
at: IOUtil.makePipe(Native Method)" trace?

**Comment by piotrnk** [comment]
@bainian12345  Thanks for responding. 
After analyzing of this issue with visualvm profiler I see there can be an issue in the com.microsoft.azure.relay.TokenRenewer class logic:
- number of 'Timer' threads is increasing constantly
- after looking into the heap, I see a huge number of java.util.TimerTask o and java.util.TimerTask objects
- in azure-relay-lib the timers are created in the class: TokenRenewer 
So the first conclusion is that there might be an issue in the token renewal process.
Added logs and the profiler screenshots here: https://drive.google.com/open?id=1KSM0Zprk_APcB-g1hOSjK65Y9MTQibuy

**Comment by jfggdl** [comment]
@piotrnk The fix is checked in and will be included with the next release which should occur by March/April.

**Comment by jfggdl** [comment]
@piotrnk, this issue is fixed in https://github.com/Azure/azure-relay-java/releases/tag/0.0.3. I am closing this issue, but please feel to request to reopen this issue if you still have some questions/comments.
