### ISSUE TITLE
No proper release management

### ISSUE THREAD

**Issue by consultantleon** [Azure/azure-relay-java#59]
Hi, we try to use this API for a production solution and we need the recent fixes made on the develop branch.
However it appears there's no proper release management and there's never been a proper release version (only 0.0.2-PREVIEW on master branch).
I think it's time to tidy up, roll version on dev branch after release (0.0.3-SNAPSHOT), and produce regular releases, artifacts on maven central, and tag the releases.
Could you at least:
- complete work and testing on dev branch and create release 0.0.3 (no 'PREVIEW' just a minor release?)
+ roll dev branch to 0.0.4-SNAPSHOT
- make sure the azure-relay-java artifact 0.0.3 is deployed to maven central so that we can use it directly without replicating to our in house repository + running our own release pipeline on it to build inofficial versions?

It's time Microsoft professionalises java API support for their cloud services!

**Comment by dlstucki** [comment]
I'm not pushing back just want to ask a question about expected practices. When we have a branch which does not release frequently and a fix is made how should we decide _when_ to issue a new release? One fix per release feels a bit like overkill unless someone actually asks for a new release.

**Comment by jfggdl** [comment]
@consultantleon Thanks for your comments and insights. We will make a release once we fix issue #60.

**Comment by bainian12345** [comment]
@consultantleon Thank you for your feedback. 0.0.3 has been released on Maven with all the latest updates included.

**Comment by consultantleon** [comment]
I'd say in the days of continuous integration why not produce a release on every fix, or at least weekly/monthly?
Fix 60 is critical to us and it's not even included so we can still not use this library without local fork & fix... (I provided a one line fix using the dependency that's already within the project). As long as the fix is not released and available on maven central we cannot link our project to it!

**Comment by consultantleon** [comment]
why is it labeled with enhancement? A response header with a comma breaks the interface, it's a critical bug in my view
