### ISSUE TITLE
[HTTP] Multiple headers are not supported 

### ISSUE THREAD

**Issue by mruszews** [Azure/azure-relay-java#64]
It's impossible to send a request or response containing multiple headers with the same name.

To replicate the issue add few lines to 'simple-http-demo' (HttpSender.java):

```
// Sending an HTTP request to the listener
// To send a message body, use POST
conn.setRequestMethod((message == null || message.length() == 0) ? "GET" : "POST");
conn.setRequestProperty("ServiceBusAuthorization", tokenString);

// add 2 headers with the same name
conn.setRequestProperty("Content-Type", "application/json");
conn.addRequestProperty("Content-Type", "application/xml");
```

**Comment by dlstucki** [comment]
Will you share the call stack? In this example the HTTP sender doesn't use anything relay specific other than the library to help format the auth header. It's very likely the error is from URLConnection class itself.

[URLConnection.addRequestProperty docs](https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html#addRequestProperty-java.lang.String-java.lang.String-) state: 
> This method will not overwrite existing values associated with the same key.

[URLConnection.setRequestProperty](https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html#setRequestProperty-java.lang.String-java.lang.String-) docs suggest that using comma separated values is the solution here when using Java's URLConnection class:
> Sets the general request property. If a property with the key already exists, overwrite its value with the new value.
> NOTE: HTTP requires all request properties which can legally have multiple instances with the same key to use a comma-separated list syntax which enables multiple properties to be appended into a single property.

Can you try your scenario using comma separated values and not calling addRequestProperty if a value already exists?

**Comment by mruszews** [comment]
Thanks for quick response.
Indeed coma separated values would work. However we'd like to investigate more double headers scenario.

I agree with your comment about URlConnection. Nonetheless this example wasn't exactly reflecting our case.
We use HybridConnectionListeners (https://github.com/Azure/azure-relay-java#creating-listeners) for communication. 

Stacktrace:
==> java.io.IOException - java.lang.RuntimeException: org.eclipse.jetty.io.EofException
      at: HybridHttpConnection$ResponseStream.write(HybridHttpConnection.java:381)
  - Cause: java.lang.RuntimeException - org.eclipse.jetty.io.EofException
      at: RelayLogger.throwingException(RelayLogger.java:77)
  - Cause: org.eclipse.jetty.io.EofException
      at: ChannelEndPoint.flush(ChannelEndPoint.java:286)
  - Cause: java.io.IOException - An existing connection was forcibly closed by the remote host
      at: SocketDispatcher.write0(Native Method)

Does it make any difference?

**Comment by dlstucki** [comment]
To clarify, you're calling `context.getResponse().getHeaders().put(...)` multiple times with the same key? If the keys are the same how does it hold two values for the same header name?

@bainian12345 want to take a look?

**Comment by mruszews** [comment]
Good point. 
Seems like we've got an issue on our side. 
Let us investigate more 1-2 days, before closing this issue.

Thanks!
