### ISSUE TITLE
unnecessary dependency

### ISSUE THREAD

**Issue by consultantleon** [Azure/azure-relay-java#72]
Could you please remove the dependency

		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
			<version>7.0</version>
		</dependency>

It's only used for IllegalStateException it seems!

Pulling this transitive dependency in our project is disturbing as we have a j2se project and it creates conflicts on many levels and we're excluding dependencies to be able to work with it.

I've excluded the dependency and removed line 7 from RelayLogger:
import javax.resource.spi.IllegalStateException;

And then the project builds just fine using java.lang.IllegalStateException (line 63 of RelayLogger).

**Comment by consultantleon** [comment]
I'd like to have a released version of this API so that I'll be able to directly include it in our project without a need to fork it locally.
Could you complete this issue (and any other outstanding) and finally create a release for it so that it'll be available on maven central? (the last release available on maven central is the 0.0.3 from February 2020!). Also - we start to use this in production code and maybe it's time to roll the version to 1.0.0 ?

**Comment by bainian12345** [comment]
Done in version 0.0.4.
